# Generated by Django 4.1.1 on 2022-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2vs1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
